In [418]:
import pandas as pd

In [419]:
list1 = [1,2,-3,6.3,'data value']
print(list1)

[1, 2, -3, 6.3, 'data value']

In [420]:
series1 =pd.Series(list1)
print(series1)

0             1
1             2
2            -3
3           6.3
4    data value
dtype: object

In [421]:
type(series1)

pandas.core.series.Series

In [422]:
series2 = pd.Series([1,2,3,4])
print(series2)

0    1
1    2
2    3
3    4
dtype: int64

In [423]:
series2 = pd.Series([1,2,3,4], index = ['a','b','c','d'], dtype = float)
print(series2)

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64

In [424]:
series2 = pd.Series(1, index = ['a','b','c','d'], dtype = float)
print(series2)

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

In [425]:
series3 = pd.Series({'a':1,'b':2})
series3

a    1
b    2
dtype: int64

In [426]:
max(series3)

2

In [427]:
lst = ['a','b','c']
lst

['a', 'b', 'c']

In [428]:
df1 = pd.DataFrame(lst)
df1

   0
0  a
1  b
2  c

In [429]:
lst2 = [[1,2,3],[3,4,5],[6,7,8]]

In [430]:
pd.DataFrame(lst2)

   0  1  2
0  1  2  3
1  3  4  5
2  6  7  8

In [431]:
dict1 = {'ID' : [1,2,3,4],'SN':[55,66,77,88]}
dict1

{'ID': [1, 2, 3, 4], 'SN': [55, 66, 77, 88]}

In [432]:
pd.DataFrame(dict1)

   ID  SN
0   1  55
1   2  66
2   3  77
3   4  88

In [433]:
dict2 = {'ID' : pd.Series([1,2,3,4]),'SN':pd.Series([55,66,77,88])}
dict1

{'ID': [1, 2, 3, 4], 'SN': [55, 66, 77, 88]}

In [434]:
pd.DataFrame(dict2)

   ID  SN
0   1  55
1   2  66
2   3  77
3   4  88

In [435]:
ls_dict =[{'a':1,'b':2,'d':3},{'a':44,'b':33,'c':22}]

In [436]:
pd.DataFrame(ls_dict)

    a   b    d     c
0   1   2  3.0   NaN
1  44  33  NaN  22.0

In [437]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe.csv")
df

   Student id  study hour  Sleeping hpur  Social media  Watch time  Percentage
0           1           2              9             5           5          50
1           2           6              8             0           0          80
2           3           3              8             4           4          60
3           4           0             10             5           5          45
4           5           4              7             0           0          75
5           6          10              7             0           0          96
6           7           4              6             0           0          80
7           8          10              6             0           0          90
8           9           2              5             4           4          60
9          10           6              9             0           0          85

In [438]:
df.columns

Index(['Student id', 'study hour', 'Sleeping hpur', 'Social media',
       'Watch time', 'Percentage'],
      dtype='object')

In [439]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe.csv", nrows=4) 
df

   Student id  study hour  Sleeping hpur  Social media  Watch time  Percentage
0           1           2              9             5           5          50
1           2           6              8             0           0          80
2           3           3              8             4           4          60
3           4           0             10             5           5          45

In [440]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe.csv", usecols =[0,1]) 
df

   Student id  study hour
0           1           2
1           2           6
2           3           3
3           4           0
4           5           4
5           6          10
6           7           4
7           8          10
8           9           2
9          10           6

In [441]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe.csv", skiprows=2) 
df

    2   6   8  0  0.1  80
0   3   3   8  4    4  60
1   4   0  10  5    5  45
2   5   4   7  0    0  75
3   6  10   7  0    0  96
4   7   4   6  0    0  80
5   8  10   6  0    0  90
6   9   2   5  4    4  60
7  10   6   9  0    0  85

In [442]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe.csv", skiprows=[2,5]) 
df

   Student id  study hour  Sleeping hpur  Social media  Watch time  Percentage
0           1           2              9             5           5          50
1           3           3              8             4           4          60
2           4           0             10             5           5          45
3           6          10              7             0           0          96
4           7           4              6             0           0          80
5           8          10              6             0           0          90
6           9           2              5             4           4          60
7          10           6              9             0           0          85

In [443]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe.csv", index_col = "Student id") 
df

            study hour  Sleeping hpur  Social media  Watch time  Percentage
Student id
1                    2              9             5           5          50
2                    6              8             0           0          80
3                    3              8             4           4          60
4                    0             10             5           5          45
5                    4              7             0           0          75
6                   10              7             0           0          96
7                    4              6             0           0          80
8                   10              6             0           0          90
9                    2              5             4           4          60
10                   6              9             0           0          85

In [444]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe.csv", header = 1) 
df

    1   2   9  5  5.1  50
0   2   6   8  0    0  80
1   3   3   8  4    4  60
2   4   0  10  5    5  45
3   5   4   7  0    0  75
4   6  10   7  0    0  96
5   7   4   6  0    0  80
6   8  10   6  0    0  90
7   9   2   5  4    4  60
8  10   6   9  0    0  85

In [445]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe.csv",header = None, names=['a','b','c','d','e','f'])
df

,a,b,c,d,e,f
0,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage
1,1,2,9,5,5,50
2,2,6,8,0,0,80
3,3,3,8,4,4,60
4,4,0,10,5,5,45
5,5,4,7,0,0,75
6,6,10,7,0,0,96
7,7,4,6,0,0,80
8,8,10,6,0,0,90
9,9,2,5,4,4,60
10,10,6,9,0,0,85

In [446]:
df.head()

            a           b              c             d           e           f
0  Student id  study hour  Sleeping hpur  Social media  Watch time  Percentage
1           1           2              9             5           5          50
2           2           6              8             0           0          80
3           3           3              8             4           4          60
4           4           0             10             5           5          45

In [447]:
df.head(2)  #tailk()

            a           b              c             d           e           f
0  Student id  study hour  Sleeping hpur  Social media  Watch time  Percentage
1           1           2              9             5           5          50

In [448]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe.csv",dtype = {'Student id':'float64'})
df

   Student id  study hour  Sleeping hpur  Social media  Watch time  Percentage
0         1.0           2              9             5           5          50
1         2.0           6              8             0           0          80
2         3.0           3              8             4           4          60
3         4.0           0             10             5           5          45
4         5.0           4              7             0           0          75
5         6.0          10              7             0           0          96
6         7.0           4              6             0           0          80
7         8.0          10              6             0           0          90
8         9.0           2              5             4           4          60
9        10.0           6              9             0           0          85

In [449]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv", na_values = [5,4])
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2.0,9.0,NaN,NaN,50,8.0
1,2,6.0,8.0,0.0,0.0,80,NaN
2,3,3.0,8.0,NaN,NaN,60,NaN
3,NaN,0.0,10.0,NaN,NaN,45,9.0
4,NaN,NaN,7.0,0.0,0.0,seventy five,NaN
5,6,10.0,NaN,0.0,0.0,96,7.0
6,seven,NaN,6.0,0.0,0.0,80,NaN
7,8,10.0,6.0,0.0,0.0,90,NaN
8,9,2.0,NaN,NaN,NaN,60,NaN
9,10,6.0,9.0,0.0,0.0,85,8.0

In [450]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv", na_values = {'Student id':'seven','Percentage':'seventy five'})
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1.0,2,9.0,5,5,50.0,8.0
1,2.0,6,8.0,0,0,80.0,NaN
2,3.0,3,8.0,4,4,60.0,NaN
3,NaN,0,10.0,5,5,45.0,9.0
4,5.0,4,7.0,0,0,NaN,NaN
5,6.0,10,NaN,0,0,96.0,7.0
6,NaN,4,6.0,0,0,80.0,NaN
7,8.0,10,6.0,0,0,90.0,NaN
8,9.0,2,5.0,4,4,60.0,NaN
9,10.0,6,9.0,0,0,85.0,8.0

In [451]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv", na_filter = False)
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9,5,5,50,8
1,2,6,8,0,0,80,
2,3,3,8,4,4,60,
3,,0,10,5,5,45,9
4,5,4,7,0,0,seventy five,
5,6,10,,0,0,96,7
6,seven,4,6,0,0,80,
7,8,10,6,0,0,90,
8,9,2,5,4,4,60,
9,10,6,9,0,0,85,8

In [452]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv")
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [453]:
df.isnull()

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True
2,False,False,False,False,False,False,True
3,True,False,False,False,False,False,False
4,False,False,False,False,False,False,True
5,False,False,True,False,False,False,False
6,False,False,False,False,False,False,True
7,False,False,False,False,False,False,True
8,False,False,False,False,False,False,True
9,False,False,False,False,False,False,False

In [454]:
df.isnull().sum()

Student id       1
study hour       0
Sleeping hpur    1
Social media     0
Watch time       0
Percentage       0
new              6
dtype: int64

In [455]:
df.isnull().sum().sum() ##notnull()

np.int64(8)

In [456]:
df.notnull()

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,True,True,True,True,True,True,True
1,True,True,True,True,True,True,False
2,True,True,True,True,True,True,False
3,False,True,True,True,True,True,True
4,True,True,True,True,True,True,False
5,True,True,False,True,True,True,True
6,True,True,True,True,True,True,False
7,True,True,True,True,True,True,False
8,True,True,True,True,True,True,False
9,True,True,True,True,True,True,True

In [457]:
import numpy as np
sr = pd.Series([1,2,3,np.nan,4,np.nan])
sr

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [458]:
sr.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [459]:
df.dropna()

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
9,10,6,9.0,0,0,85,8.0

In [460]:
df.dropna(axis =0)

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
9,10,6,9.0,0,0,85,8.0

In [461]:
df.dropna(axis =1)

   study hour  Social media  Watch time    Percentage
0           2             5           5            50
1           6             0           0            80
2           3             4           4            60
3           0             5           5            45
4           4             0           0  seventy five
5          10             0           0            96
6           4             0           0            80
7          10             0           0            90
8           2             4           4            60
9           6             0           0            85

In [462]:
df.dropna(how='any') #how='all'

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
9,10,6,9.0,0,0,85,8.0

In [463]:
df.dropna(thresh=2) #atleast exist 2 data in a row

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [464]:
df.dropna(subset=['new','Percentage'])

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
3,NaN,0,10.0,5,5,45,9.0
5,6,10,NaN,0,0,96,7.0
9,10,6,9.0,0,0,85,8.0

In [465]:
df.dropna(inplace= True)# update full df
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
9,10,6,9.0,0,0,85,8.0

In [466]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv")
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [467]:
df.fillna(69)

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,69.0
2,3,3,8.0,4,4,60,69.0
3,69,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,69.0
5,6,10,69.0,0,0,96,7.0
6,seven,4,6.0,0,0,80,69.0
7,8,10,6.0,0,0,90,69.0
8,9,2,5.0,4,4,60,69.0
9,10,6,9.0,0,0,85,8.0

In [468]:
df.fillna(69,inplace = True) #update
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,69.0
2,3,3,8.0,4,4,60,69.0
3,69,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,69.0
5,6,10,69.0,0,0,96,7.0
6,seven,4,6.0,0,0,80,69.0
7,8,10,6.0,0,0,90,69.0
8,9,2,5.0,4,4,60,69.0
9,10,6,9.0,0,0,85,8.0

In [469]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv")
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [470]:
df.fillna(69,limit=2)

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,69.0
2,3,3,8.0,4,4,60,69.0
3,69,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,69.0,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [471]:
df.fillna({'Student id':'absent','Sleeping hour':0,'new':'old'})

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,old
2,3,3,8.0,4,4,60,old
3,absent,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,old
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,old
7,8,10,6.0,0,0,90,old
8,9,2,5.0,4,4,60,old
9,10,6,9.0,0,0,85,8.0

In [472]:
df.fillna(method ='ffill',axis =0) #bfill

C:\Users\User\AppData\Local\Temp\ipykernel_5672\1499448364.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method ='ffill',axis =0) #bfill

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,8.0
2,3,3,8.0,4,4,60,8.0
3,3,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,9.0
5,6,10,7.0,0,0,96,7.0
6,seven,4,6.0,0,0,80,7.0
7,8,10,6.0,0,0,90,7.0
8,9,2,5.0,4,4,60,7.0
9,10,6,9.0,0,0,85,8.0

In [473]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv")
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [474]:
df.replace(to_replace ='seven',value='five')

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,NaN,0,0,96,7.0
6,five,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [475]:
df.replace('seventy five','fifty five')

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,fifty five,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [476]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv")
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [477]:
df.replace([10,5],0)

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,0,0,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,0.0,0,0,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,0,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,0,6.0,0,0,90,NaN
8,9,2,0.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [478]:
df.replace({'Percentage':'seventy five'},'none')

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,none,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [479]:
df.replace('[A-Za-z]',0, regex = True)

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,0,NaN
5,6,10,NaN,0,0,96,7.0
6,0,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [480]:
df.replace({'Student id':'[A-Za-z]'},0, regex = True)

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,NaN,0,0,96,7.0
6,0,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [481]:
df.replace('seventy five', method ='ffill')

C:\Users\User\AppData\Local\Temp\ipykernel_5672\2546831378.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace('seventy five', method ='ffill')

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,45,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [482]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv")
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [483]:
df.interpolate()

C:\Users\User\AppData\Local\Temp\ipykernel_5672\4002874584.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.000000
1,2,6,8.0,0,0,80,8.333333
2,3,3,8.0,4,4,60,8.666667
3,NaN,0,10.0,5,5,45,9.000000
4,5,4,7.0,0,0,seventy five,8.000000
5,6,10,6.5,0,0,96,7.000000
6,seven,4,6.0,0,0,80,7.250000
7,8,10,6.0,0,0,90,7.500000
8,9,2,5.0,4,4,60,7.750000
9,10,6,9.0,0,0,85,8.000000

In [484]:
df.interpolate(method='index')

C:\Users\User\AppData\Local\Temp\ipykernel_5672\2515484856.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='index')

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.000000
1,2,6,8.0,0,0,80,8.333333
2,3,3,8.0,4,4,60,8.666667
3,NaN,0,10.0,5,5,45,9.000000
4,5,4,7.0,0,0,seventy five,8.000000
5,6,10,6.5,0,0,96,7.000000
6,seven,4,6.0,0,0,80,7.250000
7,8,10,6.0,0,0,90,7.500000
8,9,2,5.0,4,4,60,7.750000
9,10,6,9.0,0,0,85,8.000000

In [485]:
df.interpolate(method='polynomial', order=1)

C:\Users\User\AppData\Local\Temp\ipykernel_5672\2987717635.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='polynomial', order=1)

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.000000
1,2,6,8.0,0,0,80,8.333333
2,3,3,8.0,4,4,60,8.666667
3,NaN,0,10.0,5,5,45,9.000000
4,5,4,7.0,0,0,seventy five,8.000000
5,6,10,6.5,0,0,96,7.000000
6,seven,4,6.0,0,0,80,7.250000
7,8,10,6.0,0,0,90,7.500000
8,9,2,5.0,4,4,60,7.750000
9,10,6,9.0,0,0,85,8.000000

In [486]:
df.interpolate(limit =1,limit_direction='backward') #start filling from backord

C:\Users\User\AppData\Local\Temp\ipykernel_5672\99130617.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit =1,limit_direction='backward') #start filling from backord

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.000000
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,8.666667
3,NaN,0,10.0,5,5,45,9.000000
4,5,4,7.0,0,0,seventy five,8.000000
5,6,10,6.5,0,0,96,7.000000
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,7.750000
9,10,6,9.0,0,0,85,8.000000

In [487]:
df.loc[2]

Student id         3
study hour         3
Sleeping hpur    8.0
Social media       4
Watch time         4
Percentage        60
new              NaN
Name: 2, dtype: object

In [488]:
df.loc[[3,2]]

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
3,NaN,0,10.0,5,5,45,9.0
2,3,3,8.0,4,4,60,NaN

In [489]:
df.loc[0:2,'new']

0    8.0
1    NaN
2    NaN
Name: new, dtype: float64

In [490]:
df.loc[df['study hour']<8]

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
6,seven,4,6.0,0,0,80,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [491]:
df.loc[df['study hour']<8,['Student id']]

  Student id
0          1
1          2
2          3
3        NaN
4          5
6      seven
8          9
9         10

In [492]:
df.iloc[2]

Student id         3
study hour         3
Sleeping hpur    8.0
Social media       4
Watch time         4
Percentage        60
new              NaN
Name: 2, dtype: object

In [493]:
df.iloc[[2]]

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
2,3,3,8.0,4,4,60,NaN

In [494]:
df.iloc[:,0] #loc cant do it

0        1
1        2
2        3
3      NaN
4        5
5        6
6    seven
7        8
8        9
9       10
Name: Student id, dtype: object

In [495]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv")
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [496]:
gr1 =df.groupby(by = 'new')
gr1

In [497]:
gr1.groups

{7.0: [5], 8.0: [0, 9], 9.0: [3]}

In [498]:
for Percentage,df1 in gr1:
    print(Percentage)

7.0
8.0
9.0

In [499]:
gr1.describe()

    study hour                                               Sleeping hpur  \
         count  mean       std   min   25%   50%   75%   max         count
new
7.0        1.0  10.0       NaN  10.0  10.0  10.0  10.0  10.0           0.0
8.0        2.0   4.0  2.828427   2.0   3.0   4.0   5.0   6.0           2.0
9.0        1.0   0.0       NaN   0.0   0.0   0.0   0.0   0.0           1.0

           ... Social media      Watch time                                 \
     mean  ...          75%  max      count mean       std  min   25%  50%
new        ...
7.0   NaN  ...         0.00  0.0        1.0  0.0       NaN  0.0  0.00  0.0
8.0   9.0  ...         3.75  5.0        2.0  2.5  3.535534  0.0  1.25  2.5
9.0  10.0  ...         5.00  5.0        1.0  5.0       NaN  5.0  5.00  5.0


      75%  max
new
7.0  0.00  0.0
8.0  3.75  5.0
9.0  5.00  5.0

[3 rows x 32 columns]

In [500]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe3.csv")
df

     id sec  class  stdhrs  sm  percentage
0  1001   A     10       5   5          50
1  1002   B     10       0   0          80
2  1003   A     10       4   4          60
3  1004   C     11       5   5          45
4  1005   C     12       0   0          75

In [501]:
gr1.groups

{7.0: [5], 8.0: [0, 9], 9.0: [3]}

In [502]:
gr1 = df.groupby('sec')
gr1

In [503]:
gr1 = df.groupby(['sec','class']).groups
gr1

{('A', 10): [0, 2], ('B', 10): [1], ('C', 11): [3], ('C', 12): [4]}

In [504]:
for sec, df1 in gr1:
    print(sec)
    print(df1)

A
10
B
10
C
11
C
12

In [505]:
list(gr1)

[('A', 10), ('B', 10), ('C', 11), ('C', 12)]

In [506]:
df.groupby('sec').get_group('A')

     id sec  class  stdhrs  sm  percentage
0  1001   A     10       5   5          50
2  1003   A     10       4   4          60

In [507]:
gr1 = df.groupby(by = 'sec')
gr1

In [508]:
gr1.sum()

       id  class  stdhrs  sm  percentage
sec
A    2004     20       9   9         110
B    1002     10       0   0          80
C    2009     23       5   5         120

In [509]:
gr1.mean()

         id  class  stdhrs   sm  percentage
sec
A    1002.0   10.0     4.5  4.5        55.0
B    1002.0   10.0     0.0  0.0        80.0
C    1004.5   11.5     2.5  2.5        60.0

In [510]:
gr1.describe()

       id                                                             class  \
    count    mean       std     min      25%     50%      75%     max count
sec
A     2.0  1002.0  1.414214  1001.0  1001.50  1002.0  1002.50  1003.0   2.0
B     1.0  1002.0       NaN  1002.0  1002.00  1002.0  1002.00  1002.0   1.0
C     2.0  1004.5  0.707107  1004.0  1004.25  1004.5  1004.75  1005.0   2.0

           ...    sm      percentage                                           \
     mean  ...   75%  max      count  mean        std   min   25%   50%   75%
sec        ...
A    10.0  ...  4.75  5.0        2.0  55.0   7.071068  50.0  52.5  55.0  57.5
B    10.0  ...  0.00  0.0        1.0  80.0        NaN  80.0  80.0  80.0  80.0
C    11.5  ...  3.75  5.0        2.0  60.0  21.213203  45.0  52.5  60.0  67.5


      max
sec
A    60.0
B    80.0
C    75.0

[3 rows x 40 columns]

In [511]:
gr1.agg(['sum','max','mean'])

       id               class           stdhrs           sm           \
      sum   max    mean   sum max  mean    sum max mean sum max mean
sec
A    2004  1003  1002.0    20  10  10.0      9   5  4.5   9   5  4.5
B    1002  1002  1002.0    10  10  10.0      0   0  0.0   0   0  0.0
C    2009  1005  1004.5    23  12  11.5      5   5  2.5   5   5  2.5

    percentage
           sum max  mean
sec
A          110  60  55.0
B           80  80  80.0
C          120  75  60.0

In [512]:
df1 =pd.DataFrame({'id':[1,2,3,4],
                   'name':['A','B','C','D']})

In [513]:
df2 =pd.DataFrame({'id':[1,2,3,5],
                   'class':['F','G','H','I']})

In [514]:
pd.merge(df1,df2, on='id')

   id name class
0   1    A     F
1   2    B     G
2   3    C     H

In [515]:
pd.merge(df1,df2, on='id',how='outer')

   id name class
0   1    A     F
1   2    B     G
2   3    C     H
3   4    D   NaN
4   5  NaN     I

In [516]:
pd.merge(df1,df2, on='id',how='outer',indicator = True)

   id name class      _merge
0   1    A     F        both
1   2    B     G        both
2   3    C     H        both
3   4    D   NaN   left_only
4   5  NaN     I  right_only

In [517]:
df2 =pd.DataFrame({'id':[5,6,7,8],
                   'class':['F','G','H','I']})

In [518]:
pd.merge(df1,df2, on='id',how='outer')

   id name class
0   1    A   NaN
1   2    B   NaN
2   3    C   NaN
3   4    D   NaN
4   5  NaN     F
5   6  NaN     G
6   7  NaN     H
7   8  NaN     I

In [519]:
sr1 = pd.Series([1,2,3])

In [520]:
sr2 = pd.Series([4,5,6])

In [521]:
pd.concat([sr1,sr2])

0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64

In [522]:
df1 =pd.DataFrame({'id':[1,2,3,4],
             'name':['A','B','C','D'],
             'class':[5,6,7,8]})
df1

   id name  class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [523]:
df2 =pd.DataFrame({'id':[5,6,7,8],
             'name':['e','f','g','h'],
             'class':[9,10,11,12]})
df2

   id name  class
0   5    e      9
1   6    f     10
2   7    g     11
3   8    h     12

In [524]:
pd.concat([df1, df2])

   id name  class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
0   5    e      9
1   6    f     10
2   7    g     11
3   8    h     12

In [525]:
pd.concat([df1, df2], axis=1)

   id name  class  id name  class
0   1    A      5   5    e      9
1   2    B      6   6    f     10
2   3    C      7   7    g     11
3   4    D      8   8    h     12

In [526]:
pd.concat([df1, df2], ignore_index=True)

   id name  class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8
4   5    e      9
5   6    f     10
6   7    g     11
7   8    h     12

In [527]:
df1 =pd.DataFrame({'id':[1,2,3,4],
             'name':['A','B','C','D'],
             'class':[5,6,7,8]})
df1

   id name  class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [528]:
df2 =pd.DataFrame({'id':[5,6,7],
             'name':['e','f','g'],
             'class':[9,10,11]})
df2

   id name  class
0   5    e      9
1   6    f     10
2   7    g     11

In [529]:
pd.concat([df1, df2],axis=1, ignore_index=True)

   0  1  2    3    4     5
0  1  A  5  5.0    e   9.0
1  2  B  6  6.0    f  10.0
2  3  C  7  7.0    g  11.0
3  4  D  8  NaN  NaN   NaN

In [530]:
pd.concat([df1, df2],axis=1, join='inner')

   id name  class  id name  class
0   1    A      5   5    e      9
1   2    B      6   6    f     10
2   3    C      7   7    g     11

In [531]:
pd.concat([df1, df2], keys =['1st','2nd'])

       id name  class
1st 0   1    A      5
    1   2    B      6
    2   3    C      7
    3   4    D      8
2nd 0   5    e      9
    1   6    f     10
    2   7    g     11

In [532]:
pd.concat([df1, df2], keys =['1st','2nd'],axis=1)

  1st             2nd
   id name class   id name class
0   1    A     5  5.0    e   9.0
1   2    B     6  6.0    f  10.0
2   3    C     7  7.0    g  11.0
3   4    D     8  NaN  NaN   NaN

In [533]:
df1 =pd.DataFrame({'id':[1,2,3,4],
             'name':['A','B','C','D'],
             'class':[5,6,7,8]})
df1

   id name  class
0   1    A      5
1   2    B      6
2   3    C      7
3   4    D      8

In [534]:
df2 =pd.DataFrame({'id2':[5,6,7,8],
             'name2':['e','f','g','h'],
             'class2':[9,10,11,12]})
df2

   id2 name2  class2
0    5     e       9
1    6     f      10
2    7     g      11
3    8     h      12

In [535]:
df1.join(df2)

   id name  class  id2 name2  class2
0   1    A      5    5     e       9
1   2    B      6    6     f      10
2   3    C      7    7     g      11
3   4    D      8    8     h      12

In [536]:
df2 =pd.DataFrame({'id2':[5,6,7],
             'name2':['e','f','g'],
             'class2':[9,10,11]})
df2

   id2 name2  class2
0    5     e       9
1    6     f      10
2    7     g      11

In [537]:
df2 =pd.DataFrame({'id2':[5,6,7,8],
             'name2':['e','f','g','h'],
             'class2':[9,10,11,12]})
df2

   id2 name2  class2
0    5     e       9
1    6     f      10
2    7     g      11
3    8     h      12

In [538]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe.csv")
df

   Student id  study hour  Sleeping hpur  Social media  Watch time  Percentage
0           1           2              9             5           5          50
1           2           6              8             0           0          80
2           3           3              8             4           4          60
3           4           0             10             5           5          45
4           5           4              7             0           0          75
5           6          10              7             0           0          96
6           7           4              6             0           0          80
7           8          10              6             0           0          90
8           9           2              5             4           4          60
9          10           6              9             0           0          85

In [539]:
df.pivot_table(index = 'Student id', columns='Percentage')

           Sleeping hpur                                    Social media       \
Percentage            45   50   60   75   80   85   90   96           45   50
Student id
1                    NaN  9.0  NaN  NaN  NaN  NaN  NaN  NaN          NaN  5.0
2                    NaN  NaN  NaN  NaN  8.0  NaN  NaN  NaN          NaN  NaN
3                    NaN  NaN  8.0  NaN  NaN  NaN  NaN  NaN          NaN  NaN
4                   10.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN          5.0  NaN
5                    NaN  NaN  NaN  7.0  NaN  NaN  NaN  NaN          NaN  NaN
6                    NaN  NaN  NaN  NaN  NaN  NaN  NaN  7.0          NaN  NaN
7                    NaN  NaN  NaN  NaN  6.0  NaN  NaN  NaN          NaN  NaN
8                    NaN  NaN  NaN  NaN  NaN  NaN  6.0  NaN          NaN  NaN
9                    NaN  NaN  5.0  NaN  NaN  NaN  NaN  NaN          NaN  NaN
10                   NaN  NaN  NaN  NaN  NaN  9.0  NaN  NaN          NaN  NaN

            ... Watch time      study hour                                 \
Percentage  ...         90   96         45   50   60   75   80   85    90
Student id  ...
1           ...        NaN  NaN        NaN  2.0  NaN  NaN  NaN  NaN   NaN
2           ...        NaN  NaN        NaN  NaN  NaN  NaN  6.0  NaN   NaN
3           ...        NaN  NaN        NaN  NaN  3.0  NaN  NaN  NaN   NaN
4           ...        NaN  NaN        0.0  NaN  NaN  NaN  NaN  NaN   NaN
5           ...        NaN  NaN        NaN  NaN  NaN  4.0  NaN  NaN   NaN
6           ...        NaN  0.0        NaN  NaN  NaN  NaN  NaN  NaN   NaN
7           ...        NaN  NaN        NaN  NaN  NaN  NaN  4.0  NaN   NaN
8           ...        0.0  NaN        NaN  NaN  NaN  NaN  NaN  NaN  10.0
9           ...        NaN  NaN        NaN  NaN  2.0  NaN  NaN  NaN   NaN
10          ...        NaN  NaN        NaN  NaN  NaN  NaN  NaN  6.0   NaN


Percentage    96
Student id
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6           10.0
7            NaN
8            NaN
9            NaN
10           NaN

[10 rows x 32 columns]

In [540]:
df.pivot_table(index = 'Student id', columns='Percentage',aggfunc='count')

           Sleeping hpur                                    Social media       \
Percentage            45   50   60   75   80   85   90   96           45   50
Student id
1                    NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN          NaN  1.0
2                    NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN          NaN  NaN
3                    NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN          NaN  NaN
4                    1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN          1.0  NaN
5                    NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN          NaN  NaN
6                    NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0          NaN  NaN
7                    NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN          NaN  NaN
8                    NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN          NaN  NaN
9                    NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN          NaN  NaN
10                   NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN          NaN  NaN

            ... Watch time      study hour
Percentage  ...         90   96         45   50   60   75   80   85   90   96
Student id  ...
1           ...        NaN  NaN        NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN
2           ...        NaN  NaN        NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN
3           ...        NaN  NaN        NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN
4           ...        NaN  NaN        1.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5           ...        NaN  NaN        NaN  NaN  NaN  1.0  NaN  NaN  NaN  NaN
6           ...        NaN  1.0        NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
7           ...        NaN  NaN        NaN  NaN  NaN  NaN  1.0  NaN  NaN  NaN
8           ...        1.0  NaN        NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN
9           ...        NaN  NaN        NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN
10          ...        NaN  NaN        NaN  NaN  NaN  NaN  NaN  1.0  NaN  NaN

[10 rows x 32 columns]

In [541]:
df.pivot_table(index = 'Student id', columns='Percentage',aggfunc='count',fill_value=0)

           Sleeping hpur                      Social media     ... Watch time  \
Percentage            45 50 60 75 80 85 90 96           45 50  ...         90
Student id                                                     ...
1                      0  1  0  0  0  0  0  0            0  1  ...          0
2                      0  0  0  0  1  0  0  0            0  0  ...          0
3                      0  0  1  0  0  0  0  0            0  0  ...          0
4                      1  0  0  0  0  0  0  0            1  0  ...          0
5                      0  0  0  1  0  0  0  0            0  0  ...          0
6                      0  0  0  0  0  0  0  1            0  0  ...          0
7                      0  0  0  0  1  0  0  0            0  0  ...          0
8                      0  0  0  0  0  0  1  0            0  0  ...          1
9                      0  0  1  0  0  0  0  0            0  0  ...          0
10                     0  0  0  0  0  1  0  0            0  0  ...          0

              study hour
Percentage 96         45 50 60 75 80 85 90 96
Student id
1           0          0  1  0  0  0  0  0  0
2           0          0  0  0  0  1  0  0  0
3           0          0  0  1  0  0  0  0  0
4           0          1  0  0  0  0  0  0  0
5           0          0  0  0  1  0  0  0  0
6           1          0  0  0  0  0  0  0  1
7           0          0  0  0  0  1  0  0  0
8           0          0  0  0  0  0  0  1  0
9           0          0  0  1  0  0  0  0  0
10          0          0  0  0  0  0  1  0  0

[10 rows x 32 columns]

In [542]:
df.pivot_table(index = 'Student id', columns='Percentage',aggfunc='count',fill_value=0, margins = True)

           Sleeping hpur                          Social media  ...  \
Percentage            45 50 60 75 80 85 90 96 All           45  ...
Student id                                                      ...
1                      0  1  0  0  0  0  0  0   1            0  ...
2                      0  0  0  0  1  0  0  0   1            0  ...
3                      0  0  1  0  0  0  0  0   1            0  ...
4                      1  0  0  0  0  0  0  0   1            1  ...
5                      0  0  0  1  0  0  0  0   1            0  ...
6                      0  0  0  0  0  0  0  1   1            0  ...
7                      0  0  0  0  1  0  0  0   1            0  ...
8                      0  0  0  0  0  0  1  0   1            0  ...
9                      0  0  1  0  0  0  0  0   1            0  ...
10                     0  0  0  0  0  1  0  0   1            0  ...
All                    1  1  2  1  2  1  1  1  10            1  ...

           Watch time study hour
Percentage        All         45 50 60 75 80 85 90 96 All
Student id
1                   1          0  1  0  0  0  0  0  0   1
2                   1          0  0  0  0  1  0  0  0   1
3                   1          0  0  1  0  0  0  0  0   1
4                   1          1  0  0  0  0  0  0  0   1
5                   1          0  0  0  1  0  0  0  0   1
6                   1          0  0  0  0  0  0  0  1   1
7                   1          0  0  0  0  1  0  0  0   1
8                   1          0  0  0  0  0  0  1  0   1
9                   1          0  0  1  0  0  0  0  0   1
10                  1          0  0  0  0  0  1  0  0   1
All                10          1  1  2  1  2  1  1  1  10

[11 rows x 36 columns]

In [543]:
pd.melt(df)

         variable  value
0      Student id      1
1      Student id      2
2      Student id      3
3      Student id      4
4      Student id      5
5      Student id      6
6      Student id      7
7      Student id      8
8      Student id      9
9      Student id     10
10     study hour      2
11     study hour      6
12     study hour      3
13     study hour      0
14     study hour      4
15     study hour     10
16     study hour      4
17     study hour     10
18     study hour      2
19     study hour      6
20  Sleeping hpur      9
21  Sleeping hpur      8
22  Sleeping hpur      8
23  Sleeping hpur     10
24  Sleeping hpur      7
25  Sleeping hpur      7
26  Sleeping hpur      6
27  Sleeping hpur      6
28  Sleeping hpur      5
29  Sleeping hpur      9
30   Social media      5
31   Social media      0
32   Social media      4
33   Social media      5
34   Social media      0
35   Social media      0
36   Social media      0
37   Social media      0
38   Social media      4
39   Social media      0
40     Watch time      5
41     Watch time      0
42     Watch time      4
43     Watch time      5
44     Watch time      0
45     Watch time      0
46     Watch time      0
47     Watch time      0
48     Watch time      4
49     Watch time      0
50     Percentage     50
51     Percentage     80
52     Percentage     60
53     Percentage     45
54     Percentage     75
55     Percentage     96
56     Percentage     80
57     Percentage     90
58     Percentage     60
59     Percentage     85

In [544]:
df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv")
df

,Student id,study hour,Sleeping hpur,Social media,Watch time,Percentage,new
0,1,2,9.0,5,5,50,8.0
1,2,6,8.0,0,0,80,NaN
2,3,3,8.0,4,4,60,NaN
3,NaN,0,10.0,5,5,45,9.0
4,5,4,7.0,0,0,seventy five,NaN
5,6,10,NaN,0,0,96,7.0
6,seven,4,6.0,0,0,80,NaN
7,8,10,6.0,0,0,90,NaN
8,9,2,5.0,4,4,60,NaN
9,10,6,9.0,0,0,85,8.0

In [545]:
pd.melt(df, id_vars = ['Student id'], value_vars = ['study hour'])

  Student id    variable  value
0          1  study hour      2
1          2  study hour      6
2          3  study hour      3
3        NaN  study hour      0
4          5  study hour      4
5          6  study hour     10
6      seven  study hour      4
7          8  study hour     10
8          9  study hour      2
9         10  study hour      6

In [546]:
pd.melt(df, id_vars = ['Student id'], value_vars = ['study hour'],var_name='ok',value_name = 'yes')

  Student id          ok  yes
0          1  study hour    2
1          2  study hour    6
2          3  study hour    3
3        NaN  study hour    0
4          5  study hour    4
5          6  study hour   10
6      seven  study hour    4
7          8  study hour   10
8          9  study hour    2
9         10  study hour    6

In [547]:
# df =pd.read_csv(r"F:\\coding\\Dataframe\\pandasdataframe2.csv", parse-dates =['Date'])
#df